config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  devise_for :users
  resource :dashboard, only: [:show]
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end 
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    before_action :store_user_location!, if: :storable_location?
    before_action :authenticate_user!
    
    def index
        @courses = Course.search(params[:search])
    end
    
    def show
        @course = Course.find(params[:id])
    end
    
    private
    # Its important that the location is NOT stored if:
    # - The request method is not GET (non idempotent)
    # - The request is handled by a Devise controller such as Devise::SessionsController as that could cause an 
    #    infinite redirect loop.
    # - The request is an Ajax request as this can lead to very unexpected behaviour.
    def storable_location?
      request.get? && is_navigational_format? && !devise_controller? && !request.xhr? 
    end

    def store_user_location!
      # :user is the scope we are authenticating
      store_location_for(:user, request.fullpath)
    end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
    before_action :authenticate_user!
    before_action :require_authorized_for_current_course, only: [:show]
    
    def new
        @course = Course.new
    end
    
    def create
        @course = current_user.courses.create(course_params)
        if @course.valid?
            redirect_to instructor_course_path(@course)
        else
            render :new, status: :unprocessable_entity
        end
    end
    
    def show
      @section = Section.new
      @lesson = Lesson.new
    end
    
    private
    
    helper_method :current_course
    
    def current_course
      @current_course ||= Course.find(params[:id])
    end
    
   def require_authorized_for_current_course
        if current_course.user != current_user
          render plain: "Unauthorized", status: :unauthorized
        end
    end
    
    def course_params
        params.require(:course).permit(:title, :description, :cost, :image)
    end
    
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/views/courses/index.html.erb
<div class='bg-course-items'>
  <div class='course-heading'>
    <h1>Learn something today</h1>
  </div>
  <div class='select-course-content'>
    <% @courses.each do |course| %>
      <div class='course-item'>
        <h2><%= link_to course.title, course_path(course), class: 'course-title' %></h2>
              <!-- images -->
              <% if course.image.present? %>
                  <%= image_tag course.image, class: 'course-img' %>
              <% else %>
                  <%= image_tag 'default.png', class: 'course-img' %>
              <% end %>
              <!-- Description -->
              <div class="course-description">
                  <p><%= course.description %></p>
              </div>
              
              <div class="cost-sec">
                  <%= link_to 'More Details', course_path(course), class: 'more-details btn btn-primary btn-large' %>
              </div>
              
              <!-- course price -->
              <div class='cost'>
                <% if course.free? %>
                  <b>Free</b>
                <% else %>
                  <b>$<%= course.cost.to_i %></b>
                <% end %>
              </div>
        </div>
    <% end %>
  </div>
</div>

app/views/courses/show.html.erb
<div class="synopsis">
  <h1><%= @course.title %></h1>
  <div class="description">
    <p>
      <%= @course.description %>
      <br>
      <span>Created by <%= @course.user.email %></span>
    </p>
  </div>
</div>
<!-- Course description ^^ -->

<!-- Course info -->
<section class='course-body'>
  <div class='course-info'>
    <% if @course.image.present? %>
        <%= image_tag @course.image, class: 'course-img' %>
    <% else %>
        <%= image_tag 'default.png', class: 'course-img' %>
    <% end %>
      
      <% if current_user && current_user == @course.user %>
        <div class="admin-btn">
          <%= link_to 'Administrator', instructor_course_path(@course), class: 'admin-btn-text btn btn-danger btn-large' %>
        </div>
        <% elsif current_user.enrolled_in?(@course) %>
          <h3 class="badge badge-info">You Are Enrolled!</h3>
          <!-- Course information goes here -->
        <% elsif current_user && @course.free? %>
          <%= link_to 'Enroll', course_enrollments_path(@course), class: 'enroll btn btn-primary', method: :post %>
          <span class='money-back'>30 Day Money-Back Guarantee</span>
          <h3>Includes: </h3>
            <ul class='includes'>
              <li>34.5 hours on-demand video</li>
              <li>Full lifetime access</li>
              <li>Certificate of Completion</li>
            </ul>
        <% elsif current_user && @course.premium? %>
            <p>$<%= @course.cost.to_i %></p>
            <span class='money-back'>30 Day Money-Back Guarantee</span>
            <h3>Includes: </h3>
            <ul class='includes'>
              <li>34.5 hours on-demand video</li>
              <li>Full lifetime access</li>
              <li>Certificate of Completion</li>
            </ul>
            <%= form_tag course_enrollments_path(@course) do %>
              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-email="<%= current_user.email %>"
                data-description="<%= @course.title %> (<%= number_to_currency @course.cost %>)"
                data-amount="<%= (@course.cost * 100).to_i %>"
                data-locale="auto">
              </script>
            <% end %>
          <% else %>
          <h3 class="badge badge-info"><%= link_to 'Sign In to Enroll!', new_user_session_path %></h3>
        <% end %>    
    </div>
  </div>
  <!-- Course info end -->
  
  <section class="curriculum ">
    <h2>Curriculum For This Course</h2>
    <% @course.sections.each do |section| %>
      <div class="section">
        <h3 class='section-title'><%= section.title %></h3>
        <div>
          <% section.lessons.rank(:row_order).each do |lesson| %>
            <div class='lesson-title'>
              <i class="fa fa-play-circle"></i>
              <%= link_to lesson.title, lesson_url(lesson), class: 'lesson-link' %> 
              <div class='duration'><%= lesson.duration(lesson.video) %></div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </section>
  
</section>