config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  devise_for :users
  resource :dashboard, only: [:show]
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/course.rb
class Course < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_one :rating
    has_many :sections
    has_many :enrollments
    
    
    
    validates :title, presence: true
    validates :description, presence: true
    validates :cost, presence: true, numericality: { greater_than_or_equal_to: 0 }
    
    
    def free?
      cost.zero?
    end
    
    def premium?
      !free?
      
    end
    
    def self.search(term)
      where("title iLIKE ? OR description LIKE ?", "%#{term}%", "%#{term}%")
    end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
    belongs_to :course
    belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
    belongs_to :section
    mount_uploader :video, VideoUploader
    
    include RankedModel
    ranks :row_order, with_same: :section_id
    # ranks :row_order column, with same section.
    
    def next_lesson
      lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
      if lesson.blank? && section.next_section
        return section.next_section.lessons.rank(:row_order).first
      end
      return lesson
    end
    
    def duration(video)
      movie = FFMPEG::Movie.new(video.path)
      duration_sec = movie.duration.to_i
      
      return (duration_sec / 60)
    end

end

app/models/rating.rb
class Rating < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
    belongs_to :course
    has_many :lessons
    
    include RankedModel
    ranks :row_order, with_same: :course_id
    
    def next_section
      section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
      return section
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, through: :enrollments, source: :course
  
  def enrolled_in?(course)
    enrolled_courses = []
    enrollments.each do |enrollment|
      enrolled_courses << enrollment.course
    end

    return enrolled_courses.include?(course)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # The callback which stores the current location must be added before you authenticate the user 
  # as `authenticate_user!` (or whatever your resource is) will halt the filter chain and redirect 
  # before the location can be stored.
  

  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    before_action :store_user_location!, if: :storable_location?
    before_action :authenticate_user!
    
    def index
        @courses = Course.search(params[:search])
    end
    
    def show
        @course = Course.find(params[:id])
    end
    
    private
    # Its important that the location is NOT stored if:
    # - The request method is not GET (non idempotent)
    # - The request is handled by a Devise controller such as Devise::SessionsController as that could cause an 
    #    infinite redirect loop.
    # - The request is an Ajax request as this can lead to very unexpected behaviour.
    def storable_location?
      request.get? && is_navigational_format? && !devise_controller? && !request.xhr? 
    end

    def store_user_location!
      # :user is the scope we are authenticating
      store_location_for(:user, request.fullpath)
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
    before_action :authenticate_user!

    def show
    end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
    before_action :authenticate_user!
    
    def create
      if current_course.premium?
        # Amount in cents
        @amount = (current_course.cost * 100).to_i
    
        customer = Stripe::Customer.create(
          email: params[:stripeEmail],
          source: params[:stripeToken]
        )
    
        Stripe::Charge.create(
          customer: customer.id,
          amount: @amount,
          description: 'Flixter Premo Content',
          currency: 'usd'
        )
      end
        
      current_user.enrollments.create!(course: current_course)
      redirect_to course_path(current_course)
      rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to courses_path
      end
        
    
    private
    
    def current_course
      @current_course ||= Course.find(params[:course_id])
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
    before_action :authenticate_user!
    before_action :user_enrolled?
    
    def show
    end
    
    private
      
      helper_method :user_enrolled?
      def user_enrolled?
        if current_user.enrolled_in?(current_course)
          render :show
        else
          redirect_to course_path(current_course), alert: "Enroll to see course content."
        end
      end

      helper_method :current_lesson
      def current_lesson
        @current_lesson ||= Lesson.find(params[:id])
      end
      
      def current_course
        current_lesson.section.course
      end
      
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    
    def index
  
    end
    
    def privacy
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flixter</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,900" rel="stylesheet">
    <link href="https://vjs.zencdn.net/5.12.6/video-js.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Shrikhand" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" />
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    
  </head>

  <body>
    <div id='flex-content-container'>
       <%= render 'shared/nav' %>
       <%= render 'shared/alert' %>
       <%= yield %>
    </div>
  <footer>
    <div class='container'>
      <div class="row">
        <div class="col-12 col-sm-3 footer-content">
          <b>Teachers</b>
          <br />
          <%= link_to 'Teach a Course', new_instructor_course_path %>
          <br />
          <%= link_to 'My Dashboard', dashboard_path %>
        </div>
        <div class="col-12 col-sm-3 footer-content">
          <b>About</b>
          <br />
          <%= link_to 'Team', '#' %>
          <br />
          <%= link_to 'Careers', '#' %>
          <br />
          <%= link_to 'Privacy Policy', privacy_path %>
        </div>
        <div class="col-12 col-sm-3 footer-content">
          <b>Contact</b>
          <br />
          <span>
           <%= link_to 'StatsQ', '#' %>
          <br />
          <%= link_to 'Email Us', '#' %>
          <br>
           <%= link_to 'New York City', '#' %>
          </span>
        </div>
        <div class="col-12 col-sm-3 social footer-content">
          <b>Social</b>
          <br />
          <br />
          <%= link_to 'https://github.com/chris-campbell' do %>
          <span class="fa fa-github-square fa-2x social-button"></span>
          <% end %>
          <span class="fa fa-facebook-square fa-2x social-button"></span>
          <span class="fa fa-twitter-square fa-2x social-button"></span>
        </div>
      </div>
    </div>
</footer>
    <script src="https://vjs.zencdn.net/5.12.6/video.js"></script>
    <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
    <script>
      $(function() {
  
          $(".section").accordion({
            autoHeight: false,
            navigation: true,
            collapsible: true,
            animate: 300,
          });
          
      });
    </script>
  </body>
</html>

app/views/shared/_alert.html.erb
<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/shared/_nav.html.erb
<nav>
  <div class='logo'>
    <%= link_to 'MOVE', root_path, class: 'm-logo' %>
    <%= link_to 'All Courses', courses_path, class: 'all-courses' %>
  </div>
  <div class='main-nav-links'>
    <% if user_signed_in? %>
      <ul>
        <li><%= link_to 'Dashboard', dashboard_path, class: 'dashboard' %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'logout' %></li>
      </ul>
    <% else %>
      <ul>
        <li><%= link_to 'Sign In', new_user_session_path, class: 'signin' %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path, class: 'signup' %></li>
      </ul>
    <% end %>
  </div>
  <div class='mobile-nav'>
    <div class='bar'></div>
    <div class='bar'></div>
    <div class='bar'></div>
  </div>
</nav>